version: '3'

services:
  selenium:
    container_name: datacats-selenium
    image: selenium/standalone-firefox
    restart: always
    shm_size: "2gb"  # Required < tmpfs

  db:
    container_name: datacats-psql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DATACATS_PSQL_PASS}
      POSTGRES_DB: datacats
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - "6961:5432"  #! Testing only!

  pgadmin:
    container_name: datacats_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATACATS_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATACATS_PGADMIN_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - "23434:80"

  backend-api:
    container_name: datacats-backend-api
    build:
      context: ./src/backend
      dockerfile: ./Dockerfile.api
    image: moretech2022-datacats-backend-api
    restart: always
    environment:  #DATACATS_API_PASSWORD: abcde is not implemented
      DATACATS_LOGGING_LEVEL: ${DATACATS_LOGGING_LEVEL}
      DATACATS_PSQL_USER: ${DATACATS_PSQL_USER}
      DATACATS_PSQL_PASS: ${DATACATS_PSQL_PASS}
      DATACATS_PSQL_HOST: ${DATACATS_PSQL_HOST}
      DATACATS_PSQL_PORT: ${DATACATS_PSQL_PORT}
    volumes:
      - ./docker/backend:/data
    ports:
      - "23432:80"
    depends_on:
      - db

  backend-parser:
    container_name: datacats-backend-parser
    build:
      context: ./src/backend
      dockerfile: ./Dockerfile.parser
    image: moretech2022-datacats-backend-parser
    restart: always
    environment:  #DATACATS_API_PASSWORD: abcde is not implemented
      DATACATS_LOGGING_LEVEL: ${DATACATS_LOGGING_LEVEL}
      DATACATS_PSQL_USER: ${DATACATS_PSQL_USER}
      DATACATS_PSQL_PASS: ${DATACATS_PSQL_PASS}
      DATACATS_PSQL_HOST: ${DATACATS_PSQL_HOST}
      DATACATS_PSQL_PORT: ${DATACATS_PSQL_PORT}
      DATACATS_SELENIUM_DOMAIN: ${DATACATS_SELENIUM_DOMAIN}
      DATACATS_SELENIUM_PORT: ${DATACATS_SELENIUM_PORT}
    volumes:
      - ./docker/backend:/data
    ports:
      - "23433:80"  # Persist until a scheduler is live
    depends_on:
      - db
