version: '3'

services:
  selenium:
    container_name: datacats-selenium-testing
    image: selenium/standalone-firefox
    restart: always
    ports:
      - "23436:4444"  # API and web UI
      - "7900:7900"  # VNC
    shm_size: "2gb"  # Required < tmpfs

  db:
    container_name: datacats-psql-testing
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DATACATS_PSQL_PASS}
      POSTGRES_DB: datacats
    volumes:
      - ./docker/postgres:/data/postgres
    ports:
      - "23434:5432"

  pgadmin:
    container_name: datacats_pgadmin-testing
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATACATS_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATACATS_PGADMIN_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    ports:
      - "23435:80"

  backend:
    container_name: datacats-backend-testing
    build:
      context: ./src/backend
    restart: always
    image: moretech2022-datacats-backend-testing
    environment:  #DATACATS_API_PASSWORD: abcde is not implemented
      DATACATS_LOGGING_LEVEL: ${DATACATS_LOGGING_LEVEL}
      DATACATS_PSQL_USER: ${DATACATS_PSQL_USER}
      DATACATS_PSQL_PASS: ${DATACATS_PSQL_PASS}
      DATACATS_PSQL_HOST: ${DATACATS_PSQL_HOST}
      DATACATS_PSQL_PORT: ${DATACATS_PSQL_PORT}
      DATACATS_SELENIUM_DOMAIN: ${DATACATS_SELENIUM_DOMAIN}
      DATACATS_SELENIUM_PORT: ${DATACATS_SELENIUM_PORT}
    volumes:
      - ./docker/backend:/data
    ports:
      - "23433:80"
    depends_on:
      - db
      - selenium
